arcerojas/Predio/urls.py
from django.urls import  path
from .views import Predioview,Predioinsertar,Predioeditar,Predioeliminar
urlpatterns = [
    path('', Predioview.as_view(), name='predios'),
    path('predio/new/', Predioinsertar.as_view(), name='Insertar'),
    path('Predio/Editar/<int:pk>', Predioeditar.as_view(), name='Editar'),
    path('predio/eliminar/<int:pk>', Predioeliminar.as_view(), name='Eliminar'),
]

arcerojas/arcerojas/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('inicio.urls', 'inicio'), namespace='inicio')),    
    path('Cliente/', include(('Cliente.urls', 'Cliente'), namespace='Persona')),
    path('Predio/', include(('Predio.urls', 'Predio'), namespace='Predio')),
    path('Propietario/', include(('Propietario.urls', 'Propietario'), namespace='Propietario')),
    path('Busqueda/', include(('consulta.urls', 'Consulta'), namespace='Consulta')),
   
    
]

arcerojas/Predio/models.py
from django.db import models
from TipoGeografia.models import TipoGeografia
class Predio(models.Model):
    Ubicacion = models.CharField(max_length=200)
    TipoGeografia = models.ForeignKey(TipoGeografia, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.Ubicacion)
class Meta:
      verbose_name_plural='Predios'

arcerojas/Predio/forms.py
from django import forms
from .models import Predio


class Predioform(forms.ModelForm):
    class Meta:
        model = Predio
        fields = ['Ubicacion','TipoGeografia']
        labels = {'Ubicacion': 'Digite la ubicacion ',
                  'TipoGeografia': 'Seleccione el tipo de geografia'
                 }
        widget = {'Ubicacion': forms.TextInput(),
                  'TipoGeografia': forms.TextInput(),
                 }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'})

arcerojas/Predio/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import Predioform
from .models import Predio

class Predioview(generic.ListView):
    model = Predio
    template_name = 'listpredio.html'
    context_object_name = 'predio'
class Predioinsertar(generic.CreateView):
    model = Predio
    context_object_name = 'predio'
    template_name = 'formpredio.html'
    form_class = Predioform
    success_url = reverse_lazy("Predio:predios")
   
class Predioeditar(generic.UpdateView):
    model = Predio
    context_object_name = 'predio'
    template_name = 'formpredio.html'
    form_class = Predioform
    success_url = reverse_lazy("Predio:predios")

class Predioeliminar(generic.DeleteView):
    model = Predio
    context_object_name = 'predio'
    template_name = 'deletepredio.html'
    form_class = Predioform
    success_url = reverse_lazy("Predio:predios")
   

arcerojas/Predio/templates/deletepredio.html
{% extends 'inicio.html' %}
{% block contenido %}
<div id="fondoc">

</div>
           <form method="post">

<div class="modal" tabindex="-1" role="dialog" id="elminarModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Eliminar predio</h5>
               
            </div>
            <div class="modal-body">
   
                  <div class="panel panel-default">
                      <div class="panel-heading">
                          Eliminar
                      </div>
                      <div class="panel-body">
                          {% csrf_token %}
                          <div class="alert alert-succes">
                      
                           
                                 <a href="{% url 'Predio:predios' %}" class="btn btn-succes">
                                     <span class="fa fa-undo"></span>
                                 </a>
                            
                          </div>
                      </div>
        
            </div>
            <div class="modal-footer">
                   <button type="submit" class="btn btn-danger">
                      
                       Eliminar

                   </button>
               
            </div>
        </div>
    </div>
</div>
      </form>
{% endblock contenido %}

arcerojas/Predio/templates/formpredio.html
{% extends 'inicio.html' %}
{% block contenido %}
 
 <form method="post">
     <div class="modal" tabindex="-1" role="dialog" id="elminarModal">
         <div class="modal-dialog" role="document">
             <div class="modal-content">
                 <div class="modal-header">
                     <h5 class="modal-title">Predio</h5>
                      <a  class="close" aria-label="Close" href="{% url 'Predio:predios' %}"><span aria-hidden="true">&times;</span></a>
                 </div>
                 <div class="modal-body">
                     <div class="card container-fluid" style="width: 18rem;">
                         <div class="card-body">

                             <div class="panel panel-default">
                                 <div class="panel-heading">
                                 </div>
                                 <div class="panel-body">
                                     {% csrf_token %}
                                     {{form.as_p}}
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="modal-footer">
                     <button type="submit" class="btn btn-danger">
                         Guardar
                     </button>
                 </div>
             </div>
         </div>
 </form>

{% endblock contenido %}

arcerojas/Predio/templates/listpredio.html
{% extends 'inicio.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <br>
    <div class="panel-heading">

        <a class="btn btn-outline-primary float-right" href="{% url 'Predio:Insertar' %}"><i class="bi bi-plus-circle-fill " style="font-size: 1.2rem;"></i>&nbsp; Agregar predio</a>
        
        <h1>
           <i class="bi bi-file-ruled-fill"></i>&nbsp; Predios
        </h1>
    </div>
</div>
<div class="panel-body col-md-10 container-md">
    <div class="table-stats order-table ov-h">
        <table class="table ">
            <thead>
                <tr>
                    <th class="serial">ID</th>
                    <th>Ubicacion</th>
                     <th>Tipo de geografia</th>
                    <th>Acciones</th>
                 </tr>
            </thead>
            {% csrf_token %}
            <tbody>
                {% for item in predio  %}
                <tr>
                    <td class="serial"> {{item.id}}</td>

                    <td> <span class="name">{{item.Ubicacion}}</span> </td>
                    <td>
                        <span class="name">{{item.TipoGeografia}}</span>
                    </td>
                    <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
                            onclick="url('{% url 'Predio:Eliminar' item.id  %}','{% url 'Predio:Editar' item.id  %}','{{item.id}}')">
                             <i class="bi bi-wrench"></i>&nbsp; Acciones
                             
                        </button>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div> <!-- /.table-stats -->
</div>
<div class="modal"  id="exampleModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Acciones para este predio</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="Animation(0)">
                    <i class="bi bi-x-square" style="font-size: 2rem;"></i>
                </button>
            </div>
            <div class="modal-body">
               <a id="editar" type="button" class="btn btn-success"><i class="bi bi-pencil-square"></i> &nbsp; Editar</a>
               <a id="eliminar" type="button" class="btn btn-danger" ><i class="bi bi-trash-fill"></i> &nbsp; Eliminar</a>
 
            </div>


        </div>
    </div>
</div>


<script>
    function url(string1, string2, string3, string4){
        $("#eliminar").attr('href',string1)
        $("#editar").attr('href',string2)
        $("#agragarrol").attr('href',string3)
        document.getElementById("name").value =string4
        $("#name").hide();
        sessionStorage['idcaso']=string4;
        Animation(250)
    }
</script>
{%endblock contenido%}